name: "Dokku Deploy action"
author: "Ido Berkovich"
description: "Deploy to a dokku instance using Github actions"
branding:
  icon: "upload-cloud"
  color: "green"
inputs:
  ssh-private-key:
    description: "The ssh private key to the dokku instance. WARNING: use a secret! Do not pass a plain text value!"
    required: true
  dokku-user:
    description: "The user to use for ssh (Default: dokku)"
    required: false
    default: "dokku"
  dokku-hostname:
    description: "The dokku host name to ssh into"
    required: true
  dokku-hostport:
    description: "The dokku host port to ssh into"
    required: false
    default: "22"
  app-name:
    description: "The dokku app name"
    required: true
  remote-branch:
    description: "The branch to push on the remote repository (Default: master)"
    required: false
    default: "master"
  git-push-flags:
    description: "Additional flags to be passed to the git push command. Could be used to force push"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ssh-private-key }}
    - ${{ inputs.dokku-user }}
    - ${{ inputs.dokku-hostname }}
    - ${{ inputs.dokku-hostport }}
    - ${{ inputs.app-name }}
    - ${{ inputs.remote-branch }}
    - ${{ inputs.git-push-flags }}
